### PR TITLE
#164859746 User authentication with JWT generation

### PR DESCRIPTION
**Pull request by wekesa931**
**What does this PR do?**

**Description of Task to be completed?**

- [x] Create an endpoint that allows anyone to signup for an account in the application
- [x] Upon signup a json web token should be generated to allow the user access other routes in the application
- [x] Write relevant tests for the created endpoint

**How should this be manually tested?**
1. Clone the repo
```
$ git clone https://github.com/andela/ah-django
```
2. Create a virtual environment with pipenv
```
$ pipenv shell
```
3. Configure the database to work with the application
```
$ python manage.py makemigrations
$ python manage.py migrate
```
4. Run the application
```
$ python manage.py runserver
```
5. Test with postman 
```
 {"user":{
	        "username": "boniface",
	        "email": "boniface@gmail.com",
	        "bio": "I love code",
	        "password": "bony@12345"
	}
}
```

**Any background context you want to provide?**

This implementation will improve the efficiency of the application since the user can access other routes in the application on signup without needing to log in.

**What are the relevant pivotal tracker stories?**
[](https://www.pivotaltracker.com/n/projects/2241721/stories/story_id)
#164859746 Users should receive a JWT on successful Registration

**Screenshots (if appropriate)**
image

### CODE REVIEW

**Review by wangonya — COMMENTED** [review]
I think we're getting things a little bit mixed up. Are we using pip or pipenv? Because there's already a `requirements.txt` file which would tell heroku for example or travis to do a `pip install`. Wouldn't a `Pipfile` bring conflicts? @hogum I also noticed you used pipenv if I'm not wrong? @philophilo please advice.

**Comment by wekesa931** [comment]
@wangonya I agree. I will, however, ensure I do 'pipfreeze' every time I install a dependency with 'pipenv'

**Comment by willeswa** [comment]
> I think we're getting things a little bit mixed up. Are we using pip or pipenv? Because there's already a `requirements.txt` file which would tell heroku for example or travis to do a `pip install`. Wouldn't a `Pipfile` bring conflicts? @hogum I also noticed you used pipenv if I'm not wrong? @philophilo please advice.

Worthy to note. I have been using pip too and now just you have mention it, I would want to know if it does affect some builds. I have also configured the .travis.yml file to use pip.

**Comment by mugoh** [comment]
> I think we're getting things a little bit mixed up. Are we using pip or pipenv? Because there's already a `requirements.txt` file which would tell heroku for example or travis to do a `pip install`. Wouldn't a `Pipfile` bring conflicts? @hogum I also noticed you used pipenv if I'm not wrong? @philophilo please advice.

Mixing up the two might raise issues. Good you've brought this up @wangonya

**Review by willeswa — CHANGES_REQUESTED** [review]
I tried testing the feature by following the instructions on the repo but couldn't. I think the problem is you are pointing to the wrong repo. Also, doing a ```pipenv``` defaults to installing dependencies in python2. Is this something you have in mind? If so, would you consider providing a step for specifying the installation of the same in python3?

**Comment by wekesa931** [comment]
@willeswa I've been working on Python 3. Not unless you have python 2 in your machine. I hope you have been able to test the code.

**Comment by philophilo** [comment]
Great progress, do you have a linter locally in your vscode

**Comment by wekesa931** [comment]
@philophilo I do not have linter. Let me add it

**Comment by philophilo** [comment]
@wekesa931 this is great, kindly squash all the commits into one single commit

**Comment by philophilo** [comment]
You still have two commit and they do not follow the standard. it must be one.

**Review by philophilo — APPROVED** [review]
LGTM

**Pull request merged**
