### PR TITLE
#164859743 Setup heroku

### PR DESCRIPTION
**Pull request by wangonya**
**What does this PR do?**
Sets up and deploy base application to Heroku

**Description of Task to be completed?**
- [x] Create and setup staging and prod app on heroku
- [x] Setup the apps to deploy from the correct branches
- [x] Provision heroku postgres database for both

**How should this be manually tested?**
After the first successful deployment, the prod app will be accessible [here](https://ah-django.herokuapp.com/), and the staging app will be accessible [here](https://ah-django-staging.herokuapp.com/)

**Any background context you want to provide?**
No deployment has been done as yet so the apps are not yet live.

**What are the relevant pivotal tracker stories?**
[#164859743](https://www.pivotaltracker.com/n/projects/2321584/stories/164859743)

**Screenshots (if appropriate)**
Screenshot 2019-03-26 at 12 02 33
Screenshot 2019-03-26 at 12 02 48

### CODE REVIEW

**Comment by willeswa** [comment]
Looks fine.

**Review by philophilo — CHANGES_REQUESTED** [review]
Squash the commits into one as per the guide

**Comment by wangonya** [comment]
> Squash the commits into one as per the guide

Done

**Review by philophilo — APPROVED** [review]
LGTM

**Pull request merged**
